name: "check-if-pr-exists"
description: "Check if pr from source to target already exists"
author: "Filip Jenik"
icon: "bookmark"
color: "yellow"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  source-branch:
    description: "Source branch"
    required: true
  target-branch:
    description: "Target branch"
    required: true
outputs:
  is-pr-already-created:
    description: "Is pull request from source to target already created"

runs:
  using: "node12"
  main: "dist/index.js"
